DROP TABLE IF EXISTS webhooks;
DROP TABLE IF EXISTS quota_usage;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS link_destinations;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenants;
DROP EXTENSION IF EXISTS "uuid-ossp";
